#pragma once

#define MIDI_BYTE_STATUS_MASK 0b10000000
#define MIDI_BYTE_SYSTEM_STATUS_MASK 0b11110000
#define MIDI_BYTE_SYSTEM_REALTIME_STATUS_MASK 0b11111000

#define MIDI_BYTE_SYSEX_START 0b11110000
#define MIDI_BYTE_SYSEX_END 0b11110111

#define MIDI_MFR_ID_LONG_ID_FIRST_BYTE 0b00000000

#define MIDI_BAUD_RATE _u(31250)

#define MATCHES_MASK(b, msk) ((msk & b) == msk)

#define MIDI_IS_STATUS_BYTE(b) MATCHES_MASK(b, MIDI_BYTE_STATUS_MASK)
#define MIDI_IS_DATA_BYTE(b) (!MIDI_IS_STATUS_BYTE(b))
#define MIDI_IS_SYSTEM_STATUS_BYTE(b) MATCHES_MASK(b, MIDI_BYTE_SYSTEM_STATUS_MASK)
#define MIDI_IS_SYSTEM_REALTIME_STATUS_BYTE(b) MATCHES_MASK(b, MIDI_BYTE_SYSTEM_REALTIME_STATUS_MASK)
#define MIDI_IS_CHANNEL_STATUS_BYTE(b) (!MIDI_IS_SYSTEM_STATUS_BYTE(b))
